### ISSUE TITLE
Ta une grosse tete

### ISSUE THREAD

**Issue by CrazyForge** [boermansjo/es_weaponshop#1]

**Comment by CrazyForge** [comment]
Est ce que ta un gros cerveau ?

**Comment by boermansjo** [comment]
Pourquoi ce genre de commentaires ?

**Comment by CrazyForge** [comment]
C'étais juste une question

**Comment by boermansjo** [comment]
Mais pourquoi cette question ? ...

**Comment by AnToJones** [comment]
C'est une pauvre merde Jo .... Laisse tomber !

**Comment by AnToJones** [comment]
C'est une pauvre merde Jo .... Juste bon a profiter de tes scripts et des script du forum FiveM il n'a pas de personnalité donc il attaque le physique ...Laisse tomber !
Un pauvre con****d comme ça ne mérite même pas une réponse ...
